"""Wiki emitter (pipeline.md §3.6, ADR-010): Knowledge IR -> OKF-conformant Markdown.

Reads Knowledge IR only (ADR-009 — never facts). Pages regenerate wholesale but
only dirty ones (ir.md: no intra-page patching); indexes and recent-changes always
regenerate (they are views over the whole state / delta log).

OKF (https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md,
v0.2 — see ADR-013 for the version-tracking/migration story): YAML frontmatter over
standard Markdown — the page set is simultaneously the human wiki and an
agent-readable knowledge bundle. `index.md` and `log.md` are reserved filenames with
spec-defined structure (§8-9): neither carries general frontmatter, and `log.md` is
a date-grouped, prose changelog distinct from `recent-changes.md` (a KC-specific,
last-compile-only convenience view — not a reserved OKF filename, so it keeps
frontmatter freely).
"""

from __future__ import annotations

import posixpath
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path

from knowledge_compiler import OKF_SPEC_VERSION, __version__
from knowledge_compiler.ir import Entity, Relationship

# entity types that own a page (normalize.md P6 owners)
PAGE_OWNER_TYPES = ("component", "api", "feature", "business_rule", "risk")

_DO_NOT_EDIT = (
    "<!-- Generated by Knowledge Compiler — do not edit. "
    "The wiki is a build artifact (ADR-010); fix the source or the compiler. -->"
)

# OKF v0.2 §7 actor convention for the `generated.by` / `verified[].by` fields.
_GENERATED_BY = f"process:knowledge-compiler/{__version__}"

# OKF v0.2 §9 log.md convention words per delta op.
_OP_LOG_LABEL = {
    "added": "**Creation**",
    "changed": "**Update**",
    "removed": "**Deprecation**",
    "moved": "**Update**",
}


@dataclass(frozen=True)
class WikiContext:
    repo_slug: str
    compile_run_id: int
    commit_sha: str
    finished_at: datetime | None = None


@dataclass(frozen=True)
class RunDelta:
    """One compile's delta-log summary for the log/recent-changes pages."""

    compile_run_id: int
    commit_sha: str
    changes: tuple[tuple[str, str, str], ...]  # (op, slug, entity_type)
    finished_at: datetime | None = None


@dataclass
class _State:
    """Index of the full current entity set, built once per emit."""

    by_slug: dict[str, Entity] = field(default_factory=dict)
    outgoing: dict[str, list[Relationship]] = field(default_factory=dict)
    incoming: dict[str, list[Relationship]] = field(default_factory=dict)


def page_path(slug: str) -> str:
    """component/billing-rules -> component/billing-rules.md (slug IS the path — ir.md §3.2)."""
    return f"{slug}.md"


def rel_link(from_slug: str, to_slug: str) -> str:
    return posixpath.relpath(page_path(to_slug), start=posixpath.dirname(page_path(from_slug)))


class WikiEmitter:
    """Emitter plugin (built-in). Returns the list of files written."""

    def __init__(self, output_dir: Path) -> None:
        self.output_dir = output_dir

    def emit(self, entities: list[Entity], relationships: list[Relationship],
             dirty: set[str] | None, recent: list[RunDelta], ctx: WikiContext) -> list[Path]:
        state = _State()
        for e in entities:
            state.by_slug[e.slug] = e
        for r in relationships:
            state.outgoing.setdefault(r.from_slug, []).append(r)
            state.incoming.setdefault(r.to_slug, []).append(r)

        written: list[Path] = []
        pages = [e for e in entities if e.entity_type == "wiki_page"]
        live_owner_slugs: set[str] = set()
        for page in sorted(pages, key=lambda e: e.slug):
            owner = state.by_slug.get(page.payload["owner_slug"])
            if owner is None:
                continue  # dangling page: owner removed this compile; page follows next diff
            live_owner_slugs.add(owner.slug)
            if dirty is not None and owner.slug not in dirty and page.slug not in dirty:
                continue  # clean page: not regenerated (delta-driven emission)
            written.append(self._write(page_path(owner.slug),
                                       self._render_page(owner, state, ctx)))

        self._prune_orphaned_pages(live_owner_slugs)

        written.append(self._write("index.md", self._render_index(state, ctx)))
        written.append(self._write("log.md", self._render_log(recent)))
        written.append(self._write("recent-changes.md", self._render_recent_changes(recent)))
        return written

    _RESERVED_FILENAMES = ("index.md", "log.md", "recent-changes.md")

    def _prune_orphaned_pages(self, live_owner_slugs: set[str]) -> None:
        """Delete on-disk pages whose owning entity no longer exists. Emission
        is otherwise additive-only (dirty-only rewrites, ir.md), so a removed
        entity's page would otherwise sit on disk forever, frozen at whatever
        content it had when last written — never regenerated (the owner-is-None
        skip above), never deleted. Runs unconditionally, independent of the
        dirty filter: it must catch both a removal from *this* compile and any
        orphan already stranded by a prior compile, and is self-healing once
        deployed regardless of --full/--pr/--emit-only."""
        if not self.output_dir.is_dir():
            return
        for existing in self.output_dir.rglob("*.md"):
            rel = existing.relative_to(self.output_dir).as_posix()
            if rel in self._RESERVED_FILENAMES:
                continue
            slug = rel[:-len(".md")]
            if slug not in live_owner_slugs:
                existing.unlink()

    # -- rendering ------------------------------------------------------------------

    def _frontmatter(self, entity: Entity, ctx: WikiContext) -> str:
        files = entity.payload.get("files") or sorted({a.file_path for a in entity.anchors})
        lines = [
            "---",
            f"type: {entity.entity_type}",
            f"title: \"{entity.name}\"",
            f"slug: {entity.slug}",
            f"repo: {ctx.repo_slug}",
            f"compile_run: {ctx.compile_run_id}",
            f"commit: {ctx.commit_sha}",
        ]
        if files:
            lines.append("files:")
            lines.extend(f"  - {f}" for f in files)
        if ctx.finished_at is not None:
            lines += ["generated:", f"  by: {_GENERATED_BY}",
                     f"  at: {ctx.finished_at.isoformat()}"]
        lines += ["---", ""]
        return "\n".join(lines)

    def _render_page(self, owner: Entity, state: _State, ctx: WikiContext) -> str:
        parts = [self._frontmatter(owner, ctx), _DO_NOT_EDIT, "", f"# {owner.name}", ""]
        render = getattr(self, f"_body_{owner.entity_type}", self._body_generic)
        parts.extend(render(owner, state))
        parts.extend(self._relations_section(owner, state))
        return "\n".join(parts).rstrip() + "\n"

    def _body_component(self, e: Entity, state: _State) -> list[str]:
        p = e.payload
        out = [f"**Kind:** {p['kind']} · **Language:** {p['language']}", ""]
        if p.get("files"):
            out += ["**Files:** " + ", ".join(f"`{f}`" for f in p["files"]), ""]
        if p.get("symbols"):
            out += ["## Symbols", "", "| Symbol | Kind |", "|---|---|"]
            out += [f"| `{s['symbol_path']}` | {s['kind']} |" for s in p["symbols"]]
            out.append("")
        if p.get("external_dependencies"):
            out += ["## External dependencies", ""]
            out += [f"- `{d}`" for d in p["external_dependencies"]]
            out.append("")
        return out

    def _body_api(self, e: Entity, state: _State) -> list[str]:
        p = e.payload
        out = [f"**`{p['method']} {p['route']}`**", ""]
        if p.get("handlers"):
            out += ["**Handlers:** " + ", ".join(f"`{h}`" for h in p["handlers"]), ""]
        if p.get("sources"):
            out += [f"**Observed via:** {', '.join(p['sources'])}", ""]
        if len(p.get("sources", [])) == 1 and p["sources"] != ["code_pattern"]:
            out += ["> ⚠ Observed in the spec but not in code (or vice versa) — "
                    "see conflict surfacing, ir.md §4.3.", ""]
        return out

    def _body_generic(self, e: Entity, state: _State) -> list[str]:
        """feature / business_rule / risk (LLM-derived; arrives phase 4) + fallback."""
        out = []
        for key in ("statement", "narrative", "description", "intent"):
            if e.payload.get(key):
                out += [str(e.payload[key]), ""]
        if e.anchors:
            out += ["**Anchored to:**", ""]
            out += [f"- `{a.file_path}`" + (f" — `{a.symbol_path}`" if a.symbol_path else "")
                    for a in e.anchors]
            out.append("")
        return out

    _RELATION_LABELS = {
        ("out", "depends_on"): "Depends on", ("in", "depends_on"): "Used by",
        ("out", "contains"): "Contains", ("in", "contains"): "Part of",
        ("in", "covers"): "Covered by tests", ("in", "defined_in"): "APIs defined here",
        ("out", "defined_in"): "Defined in", ("in", "governs"): "Governed by",
        ("out", "governs"): "Governs", ("out", "implemented_by"): "Implemented by",
        ("in", "implemented_by"): "Implements", ("out", "affects"): "Affects",
        ("in", "affects"): "Risks", ("out", "exposes"): "Exposes",
        ("in", "verified_by"): "Verifies", ("out", "verified_by"): "Verified by",
    }

    def _relations_section(self, owner: Entity, state: _State) -> list[str]:
        groups: dict[str, list[str]] = {}
        for direction, rels, pick in (("out", state.outgoing.get(owner.slug, []), lambda r: r.to_slug),
                                      ("in", state.incoming.get(owner.slug, []), lambda r: r.from_slug)):
            for r in rels:
                label = self._RELATION_LABELS.get((direction, r.relation_type))
                if label is None:
                    continue
                other = state.by_slug.get(pick(r))
                if other is None or other.entity_type == "wiki_page":
                    continue
                if other.entity_type in PAGE_OWNER_TYPES:
                    item = f"[{other.name}]({rel_link(owner.slug, other.slug)})"
                else:
                    item = f"`{other.name}`"
                groups.setdefault(label, []).append(item)
        out: list[str] = []
        for label in sorted(groups):
            out += [f"## {label}", ""]
            out += [f"- {item}" for item in sorted(set(groups[label]))]
            out.append("")
        return out

    def _render_index(self, state: _State, ctx: WikiContext) -> str:
        # OKF v0.2 §8: index.md carries NO general frontmatter — the sole sanctioned
        # exception is an optional bundle-root `okf_version`. Repo/commit/compile-run
        # context that used to live in frontmatter moves into body prose instead.
        lines = ["---", f'okf_version: "{OKF_SPEC_VERSION}"', "---", "",
                 _DO_NOT_EDIT, "", f"# {ctx.repo_slug} — engineering knowledge", "",
                 f"Repo: `{ctx.repo_slug}` · Compile run: {ctx.compile_run_id} · "
                 f"Commit: `{ctx.commit_sha[:12]}`", "",
                 "Compiled engineering knowledge. [Recent changes](recent-changes.md) · "
                 "[Log](log.md)", ""]
        for entity_type in PAGE_OWNER_TYPES:
            owners = sorted((e for e in state.by_slug.values() if e.entity_type == entity_type),
                            key=lambda e: e.slug)
            if not owners:
                continue
            title = entity_type.replace("_", " ").title()
            lines += [f"## {title}s ({len(owners)})", ""]
            lines += [f"- [{e.name}]({page_path(e.slug)})" for e in owners]
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _render_log(self, recent: list[RunDelta]) -> str:
        """OKF v0.2 §9 `log.md`: reserved filename, no frontmatter, date-grouped
        (ISO 8601 headings, newest first), prose entries. Full multi-compile
        chronological history, distinct from `recent-changes.md`'s last-compile-only
        scope."""
        lines = [_DO_NOT_EDIT, "", "# Log", ""]
        if not recent:
            lines += ["No compiles recorded yet.", ""]
            return "\n".join(lines).rstrip() + "\n"

        current_date: str | None = None
        for run in recent:
            date = run.finished_at.strftime("%Y-%m-%d") if run.finished_at else "unknown date"
            if date != current_date:
                lines += [f"## {date}", ""]
                current_date = date
            if not run.changes:
                lines += [f"No knowledge changes — compile run {run.compile_run_id} "
                         f"(`{run.commit_sha[:12]}`).", ""]
                continue
            for op, slug, entity_type in run.changes:
                label = _OP_LOG_LABEL.get(op, f"**{op.title()}**")
                lines.append(f"- {label} `{slug}` ({entity_type}) — compile run "
                            f"{run.compile_run_id} (`{run.commit_sha[:12]}`).")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _render_recent_changes(self, recent: list[RunDelta]) -> str:
        """KC-specific convenience view, not a reserved OKF filename: only the
        latest compile's delta. Frontmatter is fine here (see module docstring)."""
        lines = ["---", "title: \"Recent changes\"", "type: recent_changes",
                 "generated: true", "---", "", _DO_NOT_EDIT, "",
                 "# Recent changes (last compile)", ""]
        if not recent:
            lines.append("No compiles recorded yet.")
            return "\n".join(lines).rstrip() + "\n"
        run = recent[0]
        lines += [f"## Compile {run.compile_run_id} — `{run.commit_sha[:12]}`", ""]
        if not run.changes:
            lines += ["No knowledge changes.", ""]
        else:
            for op, slug, entity_type in run.changes:
                target = (f"[{slug}]({page_path(slug)})"
                          if entity_type in PAGE_OWNER_TYPES else f"`{slug}`")
                lines.append(f"- **{op}** {target}")
            lines.append("")
        lines.append("Full chronological history: [log.md](log.md).")
        return "\n".join(lines).rstrip() + "\n"

    # -- io ---------------------------------------------------------------------------

    def _write(self, rel: str, content: str) -> Path:
        path = self.output_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        return path
